name: Scan code with Snyk
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        id: scan
        uses: snyk/actions/node@master
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: --sarif-file-output=snyk.sarif --all-projects
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif

      - name: Checkout repo
        if: steps.scan.outcome == 'success' # To make sure the code is safe
        uses: actions/checkout@v4
        with:
          path: security_threats_safe_version

      - name: Create zip
        if: steps.scan.outcome == 'success' # To make sure the code is safe
        uses: ihiroky/archive-action@v1
        with:
          root_dir: security_threats_safe_version
          file_path: root.zip
          verbose: true

      - uses: actions/upload-artifact@v4
        if: steps.scan.outcome == 'success' # To make sure the code is safe
        with:
          name: my-artifact
          path: root.zip
