name: Scan code with Snyk
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        id: scan
        uses: snyk/actions/node@master
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: --sarif-file-output=snyk.sarif --all-projects
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif

      - name: Prepare files to archive
        if: always() #steps.scan.outcome == 'success'
        run: |
          mkdir -p root/hoge/fuga/
          touch root/hoge/fuga/file
          touch root/file
        shell: bash

      - name: Create zip
        uses: ihiroky/archive-action@v1
        with:
          root_dir: root
          file_path: root.zip
          verbose: true
